/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MainTransition: typeof import('./components/MainTransition/index.vue')['default']
    MyTransition: typeof import('./components/MyTransition/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    Transition: typeof import('./components/Transition/index.vue')['default']
    VerifyCode: typeof import('./components/VerifyCode/index.vue')['default']
  }
}
